site_name: TOFEA
repo_url: https://github.com/mrbaozi/tofea
docs_dir: docs
theme:
  name: material
nav:
  - Home: index.md
  - Reference: reference.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
